name: Build and Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Cache dependencies
      uses: actions/cache@v3  # Updated to v3
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-cache-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.1'  # Update to the Flutter version you're using

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build AppBundle
      run: flutter build appbundle --release

    - name: Run tests
      run: flutter test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: build-artifacts
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/*.aab
