name: Build and Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust Python version as needed

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential libgl1-mesa-dev libgles2-mesa-dev
        pip install --upgrade pip
        pip install kivy kivymd face_recognition facenet_pytorch

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Run tests
      run: |
        # Assuming you have test scripts or a test suite
        echo "Running tests..."
        # Example: python -m unittest discover -s tests
        # Adjust with your actual test command if needed

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          bin/*.apk
          # Add paths to any other artifacts you want to upload

    - name: Clean up
      run: |
        buildozer android clean
