name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install SDK and Accept Licenses
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip -d $ANDROID_HOME/cmdline-tools commandlinetools-linux-7583922_latest.zip
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools
        yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager "build-tools;35.0.0" "platforms;android-35"

    - name: Build with Buildozer
      run: |
        buildozer android debug
