name: Build Kivy APK

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev git
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --upgrade Cython virtualenv

    - name: Install Buildozer
      run: |
        python3 -m pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        sudo apt-get install -y libz-dev zlib1g-dev openjdk-8-jdk unzip
        buildozer android debug
