name: Build and Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          miniconda-version: 23.3.1
          
      - name: Install dependencies
        run: conda env update --file .github/workflows/environment.yml --name base

      - name: Run build
        run: |
          source activate base
          # Replace the following with your build command
          echo "Running build..."
          # Example command: buildozer android debug
          # buildozer android debug

      - name: Run tests
        run: |
          source activate base
          # Replace the following with your test command
          echo "Running tests..."
          # Example command: pytest
          # pytest
