name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
    - kivy
    - torch
    - opencv-python
    - face_recognition
    - facenet_pytorch
    - firebase_admin
