name: base
channels:
  - defaults
dependencies:
  - python=3.12.4
  - pip
  - pip:
    - kivy
    - torch
    - opencv-python-headless
    - face_recognition
    - facenet_pytorch
    - firebase-admin
